apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-demo-service.fullname" . }}
  labels:
    {{- include "k8s-demo-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-demo-service.selectorLabels" . | nindent 4 }}
